Added `ARTrustRegion`
JuliaSmoothOptimizers/SolverTools.jl pull request #210
Opened 2023-12-27 11:10 UTC by Jay-sanjay

This PR is related to  - https://github.com/JuliaSmoothOptimizers/AdaptiveRegularization.jl/issues/92

closes - https://github.com/JuliaSmoothOptimizers/AdaptiveRegularization.jl/issues/92

2023-12-29 09:08 UTC, tmigot requested changes
Could you also add a unit test for the functions defined here?

2023-12-29 09:08 UTC, tmigot commented on src/trust-region/ar-trust-region.jl
> +end
```suggestion
```

2023-12-29 09:08 UTC, tmigot commented on src/trust-region/ar-trust-region.jl
> +end
As the comment says this already exists.

2023-12-29 09:08 UTC, tmigot commented on src/trust-region/ar-trust-region.jl
> +This can be compared to https://github.com/JuliaSmoothOptimizers/SolverTools.jl/blob/main/src/trust-region/basic-trust-region.jl
```suggestion
This can be compared to `TrustRegion` or `TRONTrustRegion`.
```

2023-12-30 10:17 UTC, Jay-sanjay commented
HI @tmigot . Sir I was a bit confused with how the tests must look like. Should they just check what all things it is returning like the below once or something else is required.

```
  @testset "ARTrustRegion" begin
    Δ₀ = 0.8
    ar = ARTrustRegion(0.8)
    @test ar.α₀ == 0.8 
    @test ar.α == 0.8
    @test ar.max_α ≈ 1 / sqrt(eps(typeof(0.8)))
    @test ar.acceptance_threshold == 0.1
    @test ar.increase_threshold == 0.75
    @test ar.reduce_threshold == 0.1
    @test ar.increase_factor == 5.0
    @test ar.decrease_factor == 0.1
    @test ar.large_decrease_factor == 0.01
    @test ar.max_unsuccinarow == 30
  end
  ```
  
And also to just let you know, I have also asked you the same thing on slack, there we can take on a conversation for this :)
thanks !

2024-01-05 08:26 UTC, tmigot commented
I replied on Slack. Unit tests should check the constructors (as you suggested) but also add check for the added function.

2024-04-01 12:12 UTC, tmigot approved these changes
Thanks for the PR @Jay-sanjay ! I took the liberty to add some more tests and it looks good.

2024-04-01 12:14 UTC, merged

2024-04-01 13:10 UTC, Jay-sanjay commented
Thanks for the review @tmigot , also I was a bit curious that how come codecov passed all checks by adding extra test-cases (like 2 more extra testcases). Did they covered any edge cases ? Or what else ?

2024-04-01 13:20 UTC, tmigot commented
Yes, it was covering edge cases in the compute_r function